### ISSUE TITLE
Camera app not working - crashes at start

### ISSUE THREAD

**Issue by dapovoa** [ishanchirps/PixelUI-12.0#2]
I can't manage to put this to work. Is there any thing you could do?

**Comment by dapovoa** [comment]
@ishanchirps Thanks for this amazing ROM!

**Comment by ishanchirps** [comment]
> I can't manage to put this to work. Is there any thing you could do?

Use Gcam latest

**Comment by dapovoa** [comment]
Could you point me to that url?

**Comment by dapovoa** [comment]
@ishanchirps please, share the link

**Comment by dapovoa** [comment]
I gave up on the ROM
